[workspace]
members = ["2015", "2025", "utils", "macros"]
resolver = "3"

[workspace.dependencies]
criterion = "0.7.0"
ahash = "0.8.12"
rand = "0.9.2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
