[package]
name = "aoc-2015"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-utils = { path = "../utils/" }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "day1"
harness = false
